import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import { Inter } from "next/font/google";
import { Roboto } from 'next/font/google';
import BootstrapClient from './components/BootstrapClient.js';
import SideNav from './components/SideNav';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/auth';

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: '400', // Specify the weight you need
  subsets: ['latin'], // Specify the subsets you need
});

export const metadata = {
  title: "D1RESEARCH INTERNAL SYSTEM",
  description: "GENERATED BY D1RESEARCH",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="container-fluid">
          <div className="row">
            {session && (
              <nav className="col-md-3 col-lg-2 d-md-block bg-light sidebar">
                <SideNav />
              </nav>
            )}
            <main className={`p-md-4 col-12 ${session ? 'col-md-9 ms-sm-auto col-lg-10' : ''}`}>
              {children}
            </main>
          </div>
        </div>
        <BootstrapClient />
      </body>
    </html>
  );
}
